package ca.bc.gov.hlth.mohums.controller;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.HttpHeaders;
import org.springframework.test.context.junit4.SpringRunner;

import java.net.URI;

import static org.junit.jupiter.api.Assertions.*;

@RunWith(SpringRunner.class)
@SpringBootTest
class UsersControllerTest {

    private final UsersController u = new UsersController(null, null, vanityHostname, null);
    
    @Autowired
    private UsersController userController; 

    private static final String vanityHostname = "http://localhost";

    @Test
    void testNull() {
        Assertions.assertThrows(NullPointerException.class, () -> u.convertLocationHeader(null));
    }

    @Test
    public void testNoLocation() {
        HttpHeaders httpHeaders = new HttpHeaders();
        httpHeaders.setLocation(null);
        HttpHeaders newHeaders = u.convertLocationHeader(httpHeaders);
        assertNotNull(newHeaders);
        assertNull(newHeaders.getLocation());
    }

    @Test
    public void testEmptyLocation() {
        HttpHeaders httpHeaders = new HttpHeaders();
        httpHeaders.setLocation(URI.create(""));
        HttpHeaders newHeaders = u.convertLocationHeader(httpHeaders);
        assertNotNull(newHeaders);
        assertEquals("", newHeaders.getLocation().toASCIIString());
    }

    @Test
    public void testUserLocation() {
        HttpHeaders httpHeaders = new HttpHeaders();
        httpHeaders.setLocation(URI.create("https://common-logon-dev.hlth.gov.bc.ca/auth/admin/realms/moh_applications/users/d862b0ee-1e3f-423b-a200-55f2e8f103d9"));
        HttpHeaders newHeaders = u.convertLocationHeader(httpHeaders);
        assertNotNull(newHeaders);
        assertEquals(vanityHostname + "/users/d862b0ee-1e3f-423b-a200-55f2e8f103d9", newHeaders.getLocation().toASCIIString());
    }

    @Test
    public void testUserLocation_badGuid() {
        HttpHeaders httpHeaders = new HttpHeaders();
        httpHeaders.setLocation(URI.create("https://common-logon-dev.hlth.gov.bc.ca/auth/admin/realms/moh_applications/users/NOT_A_GUID"));
        HttpHeaders newHeaders = u.convertLocationHeader(httpHeaders);
        assertNotNull(newHeaders);
        // If the Location header doesn't match what we expect, namely /users/VALID_GUID, don't touch it.
        assertEquals("https://common-logon-dev.hlth.gov.bc.ca/auth/admin/realms/moh_applications/users/NOT_A_GUID", newHeaders.getLocation().toASCIIString());
    }
    
     //PLR 	   : dc7b9502-3ffa-4ff8-be2e-ebfebe650590
    // BCER-CP : 9ee2f550-307a-414a-bda4-d9c44235a2a4
    
    @Test
    public void testIsAuthorized_edit_PLR_readOnlyToken() {
    	String jwt = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwdG1aOTAxOXFaZU5xdS1kWmQ5YlBBdnlRVm1KMGgtblNDS0djN1J6SXAwIn0.eyJleHAiOjE3NDQ2NzA1MTAsImlhdCI6MTc0NDY3MDIxMCwiYXV0aF90aW1lIjoxNzQ0NjcwMTMwLCJqdGkiOiI2MDU2ZGExNC0yMjBiLTQwYTEtYTBhYS03NGYyMWYwODcyZjIiLCJpc3MiOiJodHRwczovL2NvbW1vbi1sb2dvbi1kZXYuaGx0aC5nb3YuYmMuY2EvYXV0aC9yZWFsbXMvbW9oX2FwcGxpY2F0aW9ucyIsImF1ZCI6IlVTRVItTUFOQUdFTUVOVC1TRVJWSUNFIiwic3ViIjoiY2YzOTg3MDUtZWY3OC00MWE4LTlhZGQtNjU5MDdhNTVhMzVlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiVVNFUi1NQU5BR0VNRU5UIiwibm9uY2UiOiIzOTkxNWY4Mi1hMjhmLTRmZTctODMxNC1jMjdhZjJlOTQ4OGQiLCJzZXNzaW9uX3N0YXRlIjoiZmE2YWQxZDItMGI0YS00ZGQyLWIyNjUtYmQ1Y2Y3NzA3MTJkIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVzb3VyY2VfYWNjZXNzIjp7IlVTRVItTUFOQUdFTUVOVCI6eyJyb2xlcyI6WyJ1c2VyLW1hbmFnZW1lbnQtYWRtaW4iXX0sIlVTRVItTUFOQUdFTUVOVC1TRVJWSUNFIjp7InJvbGVzIjpbInJlYWQtb25seS1wbHIiLCJ2aWV3LWNsaWVudC1oY2ltd2ViIiwidmlldy1jbGllbnQtbGljZW5jZS1zdGF0dXMiLCJ2aWV3LWNsaWVudC1zYS1oaWJjLXNlcnZpY2UtYmMtcG9ydGFsIiwidmlldy1jbGllbnQtc2EtZGJhYWMtcG9ydGFsIiwidmlldy1jbGllbnQtcGlkcC1zZXJ2aWNlIiwidmlldy1ncm91cHMiLCJ2aWV3LXVzZXJzIiwibWFuYWdlLXVzZXItZGV0YWlscyIsInZpZXctY2xpZW50LXBycC1zZXJ2aWNlIiwidmlldy1tZXRyaWNzIiwidmlldy1jbGllbnQtZG1mdC13ZWJhcHAiLCJ2aWV3LWNsaWVudC1waG8tcnNjIiwibWFuYWdlLW9yZyIsInZpZXctY2xpZW50LWhjYXAtZmUiLCJjcmVhdGUtdXNlciIsInZpZXctY2xpZW50LXVtYy1lMmUtdGVzdHMiLCJ2aWV3LWNsaWVudC1iY2VyLWNwIiwidmlldy1ldmVudHMiLCJ2aWV3LWNsaWVudC1tYWlkIiwidmlldy1jbGllbnQtZW1jb2QiLCJidWxrLXJlbW92YWwiLCJtYW5hZ2UtdXNlci1yb2xlcyIsInZpZXctY2xpZW50LXNhLXNmZGMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYWxsLWdyb3VwcyIsInZpZXctY2xpZW50LW1zcGRpcmVjdC1zZXJ2aWNlIiwidmlldy1jbGllbnQtaGNpbXdlYl9oZDIiXX19LCJzY29wZSI6Im9wZW5pZCBtb2hfaWRwIHByb2ZpbGUgZW1haWwgaWRpcl9hYWQiLCJzaWQiOiJmYTZhZDFkMi0wYjRhLTRkZDItYjI2NS1iZDVjZjc3MDcxMmQiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJNZWhkaSBTYWRpayIsImdyb3VwcyI6WyJDR0kgQWNjZXNzIE1hbmFnZW1lbnQgVGVhbSJdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtZXNhZGlrQGlkaXIiLCJnaXZlbl9uYW1lIjoiTWVoZGkiLCJmYW1pbHlfbmFtZSI6IlNhZGlrIiwiZW1haWwiOiJtZWhkaS5zYWRpa0BjZ2kuY29tIn0.MeAzSXmXLiiQ9niaEeI2O6W-Nrxz4c_-QKikC_bvsTHi8aZgsFaP9KowTU8209xfhh_h6_kELJQMATrzgCWZ4pvD_VrZUUvXZeRanAPJftOa3BhmHqJ-ny98RZ-RfjsPKzcEgBJD9HexEqWTWTApj3Qz_SvkGJcLAcPkttgL8E-Hxd4HGW-vTdi6szn8IyJJyORk-YfADrPq9dXIim7KJ9LMH7XDE6JfKmHcdOcvfMic5GOhVMA4DnfrVYMAjx7K_d4iHIJMB21_UE42h7Z5byXGVhn_eEQzbZwJTikksCOlt-RaLoPF9lqFWPHUMeTccE6YJMP0pUGh_lawxDnpUQ";
    boolean result = userController.isAuthorizedToEditClient(jwt, "dc7b9502-3ffa-4ff8-be2e-ebfebe650590");
    assertFalse(result);
    }
    
    @Test
    public void testIsAuthorized_edit_PLR_readOnlyAndViewClientToken() {
    	String jwt = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwdG1aOTAxOXFaZU5xdS1kWmQ5YlBBdnlRVm1KMGgtblNDS0djN1J6SXAwIn0.eyJleHAiOjE3NDQ2OTIzODcsImlhdCI6MTc0NDY5MjA4NywiYXV0aF90aW1lIjoxNzQ0Njg5NjI4LCJqdGkiOiI4MjdhYTA2Yy03ZDI0LTQ1ZmEtOWE5Ni1hMDI4MDc5MjM0YzgiLCJpc3MiOiJodHRwczovL2NvbW1vbi1sb2dvbi1kZXYuaGx0aC5nb3YuYmMuY2EvYXV0aC9yZWFsbXMvbW9oX2FwcGxpY2F0aW9ucyIsImF1ZCI6IlVTRVItTUFOQUdFTUVOVC1TRVJWSUNFIiwic3ViIjoiY2YzOTg3MDUtZWY3OC00MWE4LTlhZGQtNjU5MDdhNTVhMzVlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiVVNFUi1NQU5BR0VNRU5UIiwibm9uY2UiOiIyOTc2MGFmZC03MTE1LTQxYzktODRlMS1jMGY1N2Q1ZWY4NTciLCJzZXNzaW9uX3N0YXRlIjoiOWQzOGE3YjItMWE0Ni00ZjU0LWI0ZjctYmI2MGU3OWI0MjE5IiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVzb3VyY2VfYWNjZXNzIjp7IlVTRVItTUFOQUdFTUVOVCI6eyJyb2xlcyI6WyJ1c2VyLW1hbmFnZW1lbnQtYWRtaW4iXX0sIlVTRVItTUFOQUdFTUVOVC1TRVJWSUNFIjp7InJvbGVzIjpbInJlYWQtb25seS1wbHIiLCJ2aWV3LWNsaWVudC1oY2ltd2ViIiwidmlldy1jbGllbnQtbGljZW5jZS1zdGF0dXMiLCJ2aWV3LWNsaWVudC1zYS1oaWJjLXNlcnZpY2UtYmMtcG9ydGFsIiwidmlldy1jbGllbnQtc2EtZGJhYWMtcG9ydGFsIiwidmlldy1jbGllbnQtcGlkcC1zZXJ2aWNlIiwidmlldy1ncm91cHMiLCJ2aWV3LXVzZXJzIiwibWFuYWdlLXVzZXItZGV0YWlscyIsInZpZXctY2xpZW50LXBycC1zZXJ2aWNlIiwidmlldy1tZXRyaWNzIiwidmlldy1jbGllbnQtZG1mdC13ZWJhcHAiLCJ2aWV3LWNsaWVudC1waG8tcnNjIiwibWFuYWdlLW9yZyIsInZpZXctY2xpZW50LWhjYXAtZmUiLCJjcmVhdGUtdXNlciIsInZpZXctY2xpZW50LXVtYy1lMmUtdGVzdHMiLCJ2aWV3LWNsaWVudC1wbHIiLCJ2aWV3LWNsaWVudC1iY2VyLWNwIiwidmlldy1ldmVudHMiLCJ2aWV3LWNsaWVudC1tYWlkIiwidmlldy1jbGllbnQtZW1jb2QiLCJidWxrLXJlbW92YWwiLCJtYW5hZ2UtdXNlci1yb2xlcyIsInZpZXctY2xpZW50LXNhLXNmZGMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYWxsLWdyb3VwcyIsInZpZXctY2xpZW50LW1zcGRpcmVjdC1zZXJ2aWNlIiwidmlldy1jbGllbnQtaGNpbXdlYl9oZDIiXX19LCJzY29wZSI6Im9wZW5pZCBtb2hfaWRwIHByb2ZpbGUgZW1haWwgaWRpcl9hYWQiLCJzaWQiOiI5ZDM4YTdiMi0xYTQ2LTRmNTQtYjRmNy1iYjYwZTc5YjQyMTkiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJNZWhkaSBTYWRpayIsImdyb3VwcyI6WyJDR0kgQWNjZXNzIE1hbmFnZW1lbnQgVGVhbSJdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtZXNhZGlrQGlkaXIiLCJnaXZlbl9uYW1lIjoiTWVoZGkiLCJmYW1pbHlfbmFtZSI6IlNhZGlrIiwiZW1haWwiOiJtZWhkaS5zYWRpa0BjZ2kuY29tIn0.XJraPf3cTbkCgVwHyl8A4iCkNO3MNVNlrCA0bAHoDi57PpxvurfZAJXwSWu_kR7tS6WHIKm3V-YmrokDm7TBqw1oJ5erJQKCaXUWXf3l16MW5W4__FfqGAMe4Pnbo7riSuZXu5qHcERPyM1mY1C51zHIbPI3inBNE_oKJn3d1-5Z_kH2ADSKlLZUHCNQXQ-KeKq-D2NY-bUaJ5gVleIkwt0o42mMqGHndPPlotiJsEqaskDPFHyWB2lEIXAfXsNgiclFN_nysAmlmP9m9_FgQ0VyYJb7ToxtnHwiZHgIfC9F5pT-2xfU5vCBXttHUwZ5J4Ca_6XXO5BdeIwW7evz-Q";
    boolean result = userController.isAuthorizedToEditClient(jwt, "dc7b9502-3ffa-4ff8-be2e-ebfebe650590");
    assertTrue(result);
    }
    
    @Test
    public void testIsAuthorized_view_PLR_readOnlyToken() {
    	String jwt = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwdG1aOTAxOXFaZU5xdS1kWmQ5YlBBdnlRVm1KMGgtblNDS0djN1J6SXAwIn0.eyJleHAiOjE3NDQ2NzA1MTAsImlhdCI6MTc0NDY3MDIxMCwiYXV0aF90aW1lIjoxNzQ0NjcwMTMwLCJqdGkiOiI2MDU2ZGExNC0yMjBiLTQwYTEtYTBhYS03NGYyMWYwODcyZjIiLCJpc3MiOiJodHRwczovL2NvbW1vbi1sb2dvbi1kZXYuaGx0aC5nb3YuYmMuY2EvYXV0aC9yZWFsbXMvbW9oX2FwcGxpY2F0aW9ucyIsImF1ZCI6IlVTRVItTUFOQUdFTUVOVC1TRVJWSUNFIiwic3ViIjoiY2YzOTg3MDUtZWY3OC00MWE4LTlhZGQtNjU5MDdhNTVhMzVlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiVVNFUi1NQU5BR0VNRU5UIiwibm9uY2UiOiIzOTkxNWY4Mi1hMjhmLTRmZTctODMxNC1jMjdhZjJlOTQ4OGQiLCJzZXNzaW9uX3N0YXRlIjoiZmE2YWQxZDItMGI0YS00ZGQyLWIyNjUtYmQ1Y2Y3NzA3MTJkIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVzb3VyY2VfYWNjZXNzIjp7IlVTRVItTUFOQUdFTUVOVCI6eyJyb2xlcyI6WyJ1c2VyLW1hbmFnZW1lbnQtYWRtaW4iXX0sIlVTRVItTUFOQUdFTUVOVC1TRVJWSUNFIjp7InJvbGVzIjpbInJlYWQtb25seS1wbHIiLCJ2aWV3LWNsaWVudC1oY2ltd2ViIiwidmlldy1jbGllbnQtbGljZW5jZS1zdGF0dXMiLCJ2aWV3LWNsaWVudC1zYS1oaWJjLXNlcnZpY2UtYmMtcG9ydGFsIiwidmlldy1jbGllbnQtc2EtZGJhYWMtcG9ydGFsIiwidmlldy1jbGllbnQtcGlkcC1zZXJ2aWNlIiwidmlldy1ncm91cHMiLCJ2aWV3LXVzZXJzIiwibWFuYWdlLXVzZXItZGV0YWlscyIsInZpZXctY2xpZW50LXBycC1zZXJ2aWNlIiwidmlldy1tZXRyaWNzIiwidmlldy1jbGllbnQtZG1mdC13ZWJhcHAiLCJ2aWV3LWNsaWVudC1waG8tcnNjIiwibWFuYWdlLW9yZyIsInZpZXctY2xpZW50LWhjYXAtZmUiLCJjcmVhdGUtdXNlciIsInZpZXctY2xpZW50LXVtYy1lMmUtdGVzdHMiLCJ2aWV3LWNsaWVudC1iY2VyLWNwIiwidmlldy1ldmVudHMiLCJ2aWV3LWNsaWVudC1tYWlkIiwidmlldy1jbGllbnQtZW1jb2QiLCJidWxrLXJlbW92YWwiLCJtYW5hZ2UtdXNlci1yb2xlcyIsInZpZXctY2xpZW50LXNhLXNmZGMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYWxsLWdyb3VwcyIsInZpZXctY2xpZW50LW1zcGRpcmVjdC1zZXJ2aWNlIiwidmlldy1jbGllbnQtaGNpbXdlYl9oZDIiXX19LCJzY29wZSI6Im9wZW5pZCBtb2hfaWRwIHByb2ZpbGUgZW1haWwgaWRpcl9hYWQiLCJzaWQiOiJmYTZhZDFkMi0wYjRhLTRkZDItYjI2NS1iZDVjZjc3MDcxMmQiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJNZWhkaSBTYWRpayIsImdyb3VwcyI6WyJDR0kgQWNjZXNzIE1hbmFnZW1lbnQgVGVhbSJdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtZXNhZGlrQGlkaXIiLCJnaXZlbl9uYW1lIjoiTWVoZGkiLCJmYW1pbHlfbmFtZSI6IlNhZGlrIiwiZW1haWwiOiJtZWhkaS5zYWRpa0BjZ2kuY29tIn0.MeAzSXmXLiiQ9niaEeI2O6W-Nrxz4c_-QKikC_bvsTHi8aZgsFaP9KowTU8209xfhh_h6_kELJQMATrzgCWZ4pvD_VrZUUvXZeRanAPJftOa3BhmHqJ-ny98RZ-RfjsPKzcEgBJD9HexEqWTWTApj3Qz_SvkGJcLAcPkttgL8E-Hxd4HGW-vTdi6szn8IyJJyORk-YfADrPq9dXIim7KJ9LMH7XDE6JfKmHcdOcvfMic5GOhVMA4DnfrVYMAjx7K_d4iHIJMB21_UE42h7Z5byXGVhn_eEQzbZwJTikksCOlt-RaLoPF9lqFWPHUMeTccE6YJMP0pUGh_lawxDnpUQ";
    boolean result = userController.isAuthorizedToViewClient(jwt, "dc7b9502-3ffa-4ff8-be2e-ebfebe650590");
    assertTrue(result);
    }
    
    // BCER-CP	9ee2f550-307a-414a-bda4-d9c44235a2a4
    @Test
    public void testIsAuthorized_edit_BCER_CP_viewClientToken() {
    	String jwt = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwdG1aOTAxOXFaZU5xdS1kWmQ5YlBBdnlRVm1KMGgtblNDS0djN1J6SXAwIn0.eyJleHAiOjE3NDQ2NzA1MTAsImlhdCI6MTc0NDY3MDIxMCwiYXV0aF90aW1lIjoxNzQ0NjcwMTMwLCJqdGkiOiI2MDU2ZGExNC0yMjBiLTQwYTEtYTBhYS03NGYyMWYwODcyZjIiLCJpc3MiOiJodHRwczovL2NvbW1vbi1sb2dvbi1kZXYuaGx0aC5nb3YuYmMuY2EvYXV0aC9yZWFsbXMvbW9oX2FwcGxpY2F0aW9ucyIsImF1ZCI6IlVTRVItTUFOQUdFTUVOVC1TRVJWSUNFIiwic3ViIjoiY2YzOTg3MDUtZWY3OC00MWE4LTlhZGQtNjU5MDdhNTVhMzVlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiVVNFUi1NQU5BR0VNRU5UIiwibm9uY2UiOiIzOTkxNWY4Mi1hMjhmLTRmZTctODMxNC1jMjdhZjJlOTQ4OGQiLCJzZXNzaW9uX3N0YXRlIjoiZmE2YWQxZDItMGI0YS00ZGQyLWIyNjUtYmQ1Y2Y3NzA3MTJkIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVzb3VyY2VfYWNjZXNzIjp7IlVTRVItTUFOQUdFTUVOVCI6eyJyb2xlcyI6WyJ1c2VyLW1hbmFnZW1lbnQtYWRtaW4iXX0sIlVTRVItTUFOQUdFTUVOVC1TRVJWSUNFIjp7InJvbGVzIjpbInJlYWQtb25seS1wbHIiLCJ2aWV3LWNsaWVudC1oY2ltd2ViIiwidmlldy1jbGllbnQtbGljZW5jZS1zdGF0dXMiLCJ2aWV3LWNsaWVudC1zYS1oaWJjLXNlcnZpY2UtYmMtcG9ydGFsIiwidmlldy1jbGllbnQtc2EtZGJhYWMtcG9ydGFsIiwidmlldy1jbGllbnQtcGlkcC1zZXJ2aWNlIiwidmlldy1ncm91cHMiLCJ2aWV3LXVzZXJzIiwibWFuYWdlLXVzZXItZGV0YWlscyIsInZpZXctY2xpZW50LXBycC1zZXJ2aWNlIiwidmlldy1tZXRyaWNzIiwidmlldy1jbGllbnQtZG1mdC13ZWJhcHAiLCJ2aWV3LWNsaWVudC1waG8tcnNjIiwibWFuYWdlLW9yZyIsInZpZXctY2xpZW50LWhjYXAtZmUiLCJjcmVhdGUtdXNlciIsInZpZXctY2xpZW50LXVtYy1lMmUtdGVzdHMiLCJ2aWV3LWNsaWVudC1iY2VyLWNwIiwidmlldy1ldmVudHMiLCJ2aWV3LWNsaWVudC1tYWlkIiwidmlldy1jbGllbnQtZW1jb2QiLCJidWxrLXJlbW92YWwiLCJtYW5hZ2UtdXNlci1yb2xlcyIsInZpZXctY2xpZW50LXNhLXNmZGMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYWxsLWdyb3VwcyIsInZpZXctY2xpZW50LW1zcGRpcmVjdC1zZXJ2aWNlIiwidmlldy1jbGllbnQtaGNpbXdlYl9oZDIiXX19LCJzY29wZSI6Im9wZW5pZCBtb2hfaWRwIHByb2ZpbGUgZW1haWwgaWRpcl9hYWQiLCJzaWQiOiJmYTZhZDFkMi0wYjRhLTRkZDItYjI2NS1iZDVjZjc3MDcxMmQiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJNZWhkaSBTYWRpayIsImdyb3VwcyI6WyJDR0kgQWNjZXNzIE1hbmFnZW1lbnQgVGVhbSJdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtZXNhZGlrQGlkaXIiLCJnaXZlbl9uYW1lIjoiTWVoZGkiLCJmYW1pbHlfbmFtZSI6IlNhZGlrIiwiZW1haWwiOiJtZWhkaS5zYWRpa0BjZ2kuY29tIn0.MeAzSXmXLiiQ9niaEeI2O6W-Nrxz4c_-QKikC_bvsTHi8aZgsFaP9KowTU8209xfhh_h6_kELJQMATrzgCWZ4pvD_VrZUUvXZeRanAPJftOa3BhmHqJ-ny98RZ-RfjsPKzcEgBJD9HexEqWTWTApj3Qz_SvkGJcLAcPkttgL8E-Hxd4HGW-vTdi6szn8IyJJyORk-YfADrPq9dXIim7KJ9LMH7XDE6JfKmHcdOcvfMic5GOhVMA4DnfrVYMAjx7K_d4iHIJMB21_UE42h7Z5byXGVhn_eEQzbZwJTikksCOlt-RaLoPF9lqFWPHUMeTccE6YJMP0pUGh_lawxDnpUQ";
    boolean result = userController.isAuthorizedToEditClient(jwt, "9ee2f550-307a-414a-bda4-d9c44235a2a4");
    assertTrue(result);
    }
    
    @Test
    public void testIsAuthorized_view_BCER_CP_viewClientToken() {
    	String jwt = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwdG1aOTAxOXFaZU5xdS1kWmQ5YlBBdnlRVm1KMGgtblNDS0djN1J6SXAwIn0.eyJleHAiOjE3NDQ2NzA1MTAsImlhdCI6MTc0NDY3MDIxMCwiYXV0aF90aW1lIjoxNzQ0NjcwMTMwLCJqdGkiOiI2MDU2ZGExNC0yMjBiLTQwYTEtYTBhYS03NGYyMWYwODcyZjIiLCJpc3MiOiJodHRwczovL2NvbW1vbi1sb2dvbi1kZXYuaGx0aC5nb3YuYmMuY2EvYXV0aC9yZWFsbXMvbW9oX2FwcGxpY2F0aW9ucyIsImF1ZCI6IlVTRVItTUFOQUdFTUVOVC1TRVJWSUNFIiwic3ViIjoiY2YzOTg3MDUtZWY3OC00MWE4LTlhZGQtNjU5MDdhNTVhMzVlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiVVNFUi1NQU5BR0VNRU5UIiwibm9uY2UiOiIzOTkxNWY4Mi1hMjhmLTRmZTctODMxNC1jMjdhZjJlOTQ4OGQiLCJzZXNzaW9uX3N0YXRlIjoiZmE2YWQxZDItMGI0YS00ZGQyLWIyNjUtYmQ1Y2Y3NzA3MTJkIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVzb3VyY2VfYWNjZXNzIjp7IlVTRVItTUFOQUdFTUVOVCI6eyJyb2xlcyI6WyJ1c2VyLW1hbmFnZW1lbnQtYWRtaW4iXX0sIlVTRVItTUFOQUdFTUVOVC1TRVJWSUNFIjp7InJvbGVzIjpbInJlYWQtb25seS1wbHIiLCJ2aWV3LWNsaWVudC1oY2ltd2ViIiwidmlldy1jbGllbnQtbGljZW5jZS1zdGF0dXMiLCJ2aWV3LWNsaWVudC1zYS1oaWJjLXNlcnZpY2UtYmMtcG9ydGFsIiwidmlldy1jbGllbnQtc2EtZGJhYWMtcG9ydGFsIiwidmlldy1jbGllbnQtcGlkcC1zZXJ2aWNlIiwidmlldy1ncm91cHMiLCJ2aWV3LXVzZXJzIiwibWFuYWdlLXVzZXItZGV0YWlscyIsInZpZXctY2xpZW50LXBycC1zZXJ2aWNlIiwidmlldy1tZXRyaWNzIiwidmlldy1jbGllbnQtZG1mdC13ZWJhcHAiLCJ2aWV3LWNsaWVudC1waG8tcnNjIiwibWFuYWdlLW9yZyIsInZpZXctY2xpZW50LWhjYXAtZmUiLCJjcmVhdGUtdXNlciIsInZpZXctY2xpZW50LXVtYy1lMmUtdGVzdHMiLCJ2aWV3LWNsaWVudC1iY2VyLWNwIiwidmlldy1ldmVudHMiLCJ2aWV3LWNsaWVudC1tYWlkIiwidmlldy1jbGllbnQtZW1jb2QiLCJidWxrLXJlbW92YWwiLCJtYW5hZ2UtdXNlci1yb2xlcyIsInZpZXctY2xpZW50LXNhLXNmZGMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYWxsLWdyb3VwcyIsInZpZXctY2xpZW50LW1zcGRpcmVjdC1zZXJ2aWNlIiwidmlldy1jbGllbnQtaGNpbXdlYl9oZDIiXX19LCJzY29wZSI6Im9wZW5pZCBtb2hfaWRwIHByb2ZpbGUgZW1haWwgaWRpcl9hYWQiLCJzaWQiOiJmYTZhZDFkMi0wYjRhLTRkZDItYjI2NS1iZDVjZjc3MDcxMmQiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJNZWhkaSBTYWRpayIsImdyb3VwcyI6WyJDR0kgQWNjZXNzIE1hbmFnZW1lbnQgVGVhbSJdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtZXNhZGlrQGlkaXIiLCJnaXZlbl9uYW1lIjoiTWVoZGkiLCJmYW1pbHlfbmFtZSI6IlNhZGlrIiwiZW1haWwiOiJtZWhkaS5zYWRpa0BjZ2kuY29tIn0.MeAzSXmXLiiQ9niaEeI2O6W-Nrxz4c_-QKikC_bvsTHi8aZgsFaP9KowTU8209xfhh_h6_kELJQMATrzgCWZ4pvD_VrZUUvXZeRanAPJftOa3BhmHqJ-ny98RZ-RfjsPKzcEgBJD9HexEqWTWTApj3Qz_SvkGJcLAcPkttgL8E-Hxd4HGW-vTdi6szn8IyJJyORk-YfADrPq9dXIim7KJ9LMH7XDE6JfKmHcdOcvfMic5GOhVMA4DnfrVYMAjx7K_d4iHIJMB21_UE42h7Z5byXGVhn_eEQzbZwJTikksCOlt-RaLoPF9lqFWPHUMeTccE6YJMP0pUGh_lawxDnpUQ";
    boolean result = userController.isAuthorizedToViewClient(jwt, "9ee2f550-307a-414a-bda4-d9c44235a2a4");
    assertTrue(result);
    }

}