-- KEYCLOAK.USER_ENTITY definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE KEYCLOAK.USER_ENTITY;

CREATE SCHEMA KEYCLOAK;

CREATE TABLE KEYCLOAK.USER_ENTITY (
                                      ID VARCHAR2(36) NOT NULL,
                                      EMAIL VARCHAR2(255) NULL,
                                      EMAIL_CONSTRAINT VARCHAR2(255) NULL,
                                      EMAIL_VERIFIED NUMBER(1,0) DEFAULT 0  NOT NULL,
                                      ENABLED NUMBER(1,0) DEFAULT 0  NOT NULL,
                                      FEDERATION_LINK VARCHAR2(255) NULL,
                                      FIRST_NAME NVARCHAR2(255) NULL,
                                      LAST_NAME NVARCHAR2(255) NULL,
                                      REALM_ID VARCHAR2(255) NULL,
                                      USERNAME NVARCHAR2(255) NULL,
                                      CREATED_TIMESTAMP NUMBER(38,0) NULL,
                                      SERVICE_ACCOUNT_CLIENT_LINK VARCHAR2(255) NULL,
                                      NOT_BEFORE NUMBER(38,0) DEFAULT 0  NOT NULL,
                                      CONSTRAINT CONSTRAINT_FB PRIMARY KEY (ID),
                                      CONSTRAINT SYS_C008025 CHECK ("ID" IS NOT NULL),
                                      CONSTRAINT SYS_C008026 CHECK ("EMAIL_VERIFIED" IS NOT NULL),
                                      CONSTRAINT SYS_C008027 CHECK ("ENABLED" IS NOT NULL),
                                      CONSTRAINT SYS_C008445 CHECK ("NOT_BEFORE" IS NOT NULL),
                                      CONSTRAINT UK_DYKN684SL8UP1CRFEI6ECKHD7 UNIQUE (REALM_ID,EMAIL_CONSTRAINT),
                                      CONSTRAINT UK_RU8TT6T700S9V50BU18WS5HA6 UNIQUE (REALM_ID,USERNAME)
);
CREATE UNIQUE INDEX CONSTRAINT_FB ON KEYCLOAK.USER_ENTITY (ID);
CREATE INDEX IDX_USER_EMAIL ON KEYCLOAK.USER_ENTITY (EMAIL);
CREATE INDEX IDX_USER_SERVICE_ACCOUNT ON KEYCLOAK.USER_ENTITY (REALM_ID,SERVICE_ACCOUNT_CLIENT_LINK);
CREATE UNIQUE INDEX UK_DYKN684SL8UP1CRFEI6ECKHD7 ON KEYCLOAK.USER_ENTITY (REALM_ID,EMAIL_CONSTRAINT);
CREATE UNIQUE INDEX UK_RU8TT6T700S9V50BU18WS5HA6 ON KEYCLOAK.USER_ENTITY (REALM_ID,USERNAME);


-- KEYCLOAK.USER_ATTRIBUTE definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE KEYCLOAK.USER_ATTRIBUTE;

CREATE TABLE KEYCLOAK.USER_ATTRIBUTE (
                                         NAME VARCHAR2(255) NOT NULL,
                                         VALUE NVARCHAR2(255) NULL,
                                         USER_ID VARCHAR2(36) NOT NULL,
                                         ID VARCHAR2(36) DEFAULT 'sybase-needs-something-here'  NOT NULL,
                                         CONSTRAINT CONSTRAINT_USER_ATTRIBUTE_PK PRIMARY KEY (ID),
                                         CONSTRAINT SYS_C008023 CHECK ("NAME" IS NOT NULL),
                                         CONSTRAINT SYS_C008024 CHECK ("USER_ID" IS NOT NULL),
                                         CONSTRAINT SYS_C008249 CHECK ("ID" IS NOT NULL),
                                         CONSTRAINT FK_5HRM2VLF9QL5FU043KQEPOVBR FOREIGN KEY (USER_ID) REFERENCES KEYCLOAK.USER_ENTITY(ID)
);
CREATE UNIQUE INDEX CONSTRAINT_USER_ATTRIBUTE_PK ON KEYCLOAK.USER_ATTRIBUTE (ID);
CREATE INDEX IDX_USER_ATTRIBUTE ON KEYCLOAK.USER_ATTRIBUTE (USER_ID);
CREATE INDEX IDX_USER_ATTRIBUTE_NAME ON KEYCLOAK.USER_ATTRIBUTE (NAME,VALUE);