# This workflow check all files formatting for the front end using prettier.
name: Code formating Prettier

defaults:
  run:
    working-directory: frontend

on:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node Setup
      - uses: actions/setup-node@v3
        with:
          node-version: 14.16.1

      - name: Setup Package
        run: npm ci

      - name: Check formating
        run: npm run format:check
