# This workflow check all files formatting for the front end using prettier.
name: Code formating Prettier

defaults:
  run:
    working-directory: frontend

on:
  pull_request:
    branches:
      - master

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          only_changed: True
